### ISSUE TITLE
Log query string (name/value pairs) when sent in the URL of a GET request

### ISSUE THREAD

**Issue by stupchiy** [kyledayton/requesthub#4]
Would be great to have possibility to see query params when GET request is performed, e.g.:

**GET** `http://localhost:54321/test?name1=value1&name2=value2`

It could be presented either in "Path" or "Query string" sections. 
And also as part of "requests" endpoint(e.g.: **GET** `http://localhost:54321/test/requests`) response body.

Regards

**Comment by kyledayton** [comment]
Hi stupchiy,
I may have time to do this in the future, but not right now :(

Although PRs are gladly accepted :)

**Comment by stupchiy** [comment]
Hi kyledayton, 
Thanks for reply.
Unfortunately haven't used go before, but who knows :)

Regards

**Comment by kyledayton** [comment]
@stupchiy Thanks to @darklynx, this feature was implemented. I have accepted their PR.

**Comment by stupchiy** [comment]
Glad to hear, thx @darklynx !
